package org.metadatacenter.server.search;

public enum SearchPermissionQueueEventType {
  RESOURCE_CREATED,
  RESOURCE_COPIED,
  RESOURCE_MOVED,
  RESOURCE_DELETED,
  RESOURCE_PERMISSION_CHANGED,

  FOLDER_CREATED,
  FOLDER_MOVED,
  FOLDER_DELETED,
  FOLDER_PERMISSION_CHANGED,

  USER_CREATED,

  GROUP_MEMBERS_UPDATED,
  GROUP_DELETED;
}
