package org.metadatacenter.config.environment;

public enum CedarEnvironmentVariable {

  CEDAR_VERSION("CEDAR_VERSION"),
  CEDAR_VERSION_MODIFIER("CEDAR_VERSION_MODIFIER"),

  CEDAR_HOME("CEDAR_HOME"),
  KEYCLOAK_HOME("KEYCLOAK_HOME"),
  NGINX_HOME("NGINX_HOME"),

  CEDAR_FRONTEND_BEHAVIOR("CEDAR_FRONTEND_BEHAVIOR"),
  CEDAR_FRONTEND_TARGET("CEDAR_FRONTEND_TARGET"),
  CEDAR_HOST("CEDAR_HOST"),
  CEDAR_NET_GATEWAY("CEDAR_NET_GATEWAY"),

  CEDAR_BIOPORTAL_API_KEY("CEDAR_BIOPORTAL_API_KEY", CedarEnvironmentVariableSecure.YES),
  CEDAR_BIOPORTAL_REST_BASE("CEDAR_BIOPORTAL_REST_BASE"),

  CEDAR_ANALYTICS_KEY("CEDAR_ANALYTICS_KEY", CedarEnvironmentVariableSecure.YES),

  CEDAR_NCBI_SRA_FTP_HOST("CEDAR_NCBI_SRA_FTP_HOST"),
  CEDAR_NCBI_SRA_FTP_USER("CEDAR_NCBI_SRA_FTP_USER"),
  CEDAR_NCBI_SRA_FTP_PASSWORD("CEDAR_NCBI_SRA_FTP_PASSWORD", CedarEnvironmentVariableSecure.YES),
  CEDAR_NCBI_SRA_FTP_DIRECTORY("CEDAR_NCBI_SRA_FTP_DIRECTORY"),

  CEDAR_IMMPORT_SUBMISSION_USER("CEDAR_IMMPORT_SUBMISSION_USER"),
  CEDAR_IMMPORT_SUBMISSION_PASSWORD("CEDAR_IMMPORT_SUBMISSION_PASSWORD", CedarEnvironmentVariableSecure.YES),

  CEDAR_ADMIN_USER_PASSWORD("CEDAR_ADMIN_USER_PASSWORD", CedarEnvironmentVariableSecure.YES),
  CEDAR_ADMIN_USER_API_KEY("CEDAR_ADMIN_USER_API_KEY", CedarEnvironmentVariableSecure.YES),

  CEDAR_CADSR_ADMIN_USER_API_KEY("CEDAR_CADSR_ADMIN_USER_API_KEY", CedarEnvironmentVariableSecure.YES),

  CEDAR_NEO4J_HOST("CEDAR_NEO4J_HOST"),
  CEDAR_NEO4J_BOLT_PORT("CEDAR_NEO4J_BOLT_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_NEO4J_USER_NAME("CEDAR_NEO4J_USER_NAME"),
  CEDAR_NEO4J_USER_PASSWORD("CEDAR_NEO4J_USER_PASSWORD", CedarEnvironmentVariableSecure.YES),

  CEDAR_MONGO_APP_USER_NAME("CEDAR_MONGO_APP_USER_NAME"),
  CEDAR_MONGO_APP_USER_PASSWORD("CEDAR_MONGO_APP_USER_PASSWORD", CedarEnvironmentVariableSecure.YES),
  CEDAR_MONGO_HOST("CEDAR_MONGO_HOST"),
  CEDAR_MONGO_PORT("CEDAR_MONGO_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_ELASTICSEARCH_HOST("CEDAR_ELASTICSEARCH_HOST"),
  CEDAR_ELASTICSEARCH_TRANSPORT_PORT("CEDAR_ELASTICSEARCH_TRANSPORT_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_MESSAGING_MYSQL_HOST("CEDAR_MESSAGING_MYSQL_HOST"),
  CEDAR_MESSAGING_MYSQL_PORT("CEDAR_MESSAGING_MYSQL_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_MESSAGING_MYSQL_DB("CEDAR_MESSAGING_MYSQL_DB"),
  CEDAR_MESSAGING_MYSQL_USER("CEDAR_MESSAGING_MYSQL_USER"),
  CEDAR_MESSAGING_MYSQL_PASSWORD("CEDAR_MESSAGING_MYSQL_PASSWORD", CedarEnvironmentVariableSecure.YES),

  CEDAR_LOG_MYSQL_HOST("CEDAR_LOG_MYSQL_HOST"),
  CEDAR_LOG_MYSQL_PORT("CEDAR_LOG_MYSQL_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_LOG_MYSQL_DB("CEDAR_LOG_MYSQL_DB"),
  CEDAR_LOG_MYSQL_USER("CEDAR_LOG_MYSQL_USER"),
  CEDAR_LOG_MYSQL_PASSWORD("CEDAR_LOG_MYSQL_PASSWORD", CedarEnvironmentVariableSecure.YES),

  CEDAR_VALIDATION_ENABLED("CEDAR_VALIDATION_ENABLED", CedarEnvironmentVariableType.BOOLEAN),

  CEDAR_SUBMISSION_TEMPLATE_ID_1("CEDAR_SUBMISSION_TEMPLATE_ID_1"),
  CEDAR_SUBMISSION_TEMPLATE_ID_2("CEDAR_SUBMISSION_TEMPLATE_ID_2"),

  CEDAR_SALT_API_KEY("CEDAR_SALT_API_KEY", CedarEnvironmentVariableSecure.YES),

  CEDAR_TEST_USER1_ID("CEDAR_TEST_USER1_ID"),
  CEDAR_TEST_USER2_ID("CEDAR_TEST_USER2_ID"),

  CEDAR_TRUSTED_FOLDERS("CEDAR_TRUSTED_FOLDERS"),

  CEDAR_REDIS_PERSISTENT_HOST("CEDAR_REDIS_PERSISTENT_HOST"),
  CEDAR_REDIS_PERSISTENT_PORT("CEDAR_REDIS_PERSISTENT_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_REDIS_NONPERSISTENT_HOST("CEDAR_REDIS_NONPERSISTENT_HOST"),
  CEDAR_REDIS_NONPERSISTENT_PORT("CEDAR_REDIS_NONPERSISTENT_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_GROUP_HTTP_PORT("CEDAR_GROUP_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_GROUP_ADMIN_PORT("CEDAR_GROUP_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_GROUP_STOP_PORT("CEDAR_GROUP_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_MESSAGING_HTTP_PORT("CEDAR_MESSAGING_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_MESSAGING_ADMIN_PORT("CEDAR_MESSAGING_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_MESSAGING_STOP_PORT("CEDAR_MESSAGING_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_REPO_HTTP_PORT("CEDAR_REPO_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_REPO_ADMIN_PORT("CEDAR_REPO_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_REPO_STOP_PORT("CEDAR_REPO_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_RESOURCE_HTTP_PORT("CEDAR_RESOURCE_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_RESOURCE_ADMIN_PORT("CEDAR_RESOURCE_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_RESOURCE_STOP_PORT("CEDAR_RESOURCE_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_SCHEMA_HTTP_PORT("CEDAR_SCHEMA_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_SCHEMA_ADMIN_PORT("CEDAR_SCHEMA_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_SCHEMA_STOP_PORT("CEDAR_SCHEMA_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_SUBMISSION_HTTP_PORT("CEDAR_SUBMISSION_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_SUBMISSION_ADMIN_PORT("CEDAR_SUBMISSION_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_SUBMISSION_STOP_PORT("CEDAR_SUBMISSION_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_ARTIFACT_HTTP_PORT("CEDAR_ARTIFACT_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_ARTIFACT_ADMIN_PORT("CEDAR_ARTIFACT_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_ARTIFACT_STOP_PORT("CEDAR_ARTIFACT_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_TERMINOLOGY_HTTP_PORT("CEDAR_TERMINOLOGY_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_TERMINOLOGY_ADMIN_PORT("CEDAR_TERMINOLOGY_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_TERMINOLOGY_STOP_PORT("CEDAR_TERMINOLOGY_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_USER_HTTP_PORT("CEDAR_USER_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_USER_ADMIN_PORT("CEDAR_USER_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_USER_STOP_PORT("CEDAR_USER_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_VALUERECOMMENDER_HTTP_PORT("CEDAR_VALUERECOMMENDER_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_VALUERECOMMENDER_ADMIN_PORT("CEDAR_VALUERECOMMENDER_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_VALUERECOMMENDER_STOP_PORT("CEDAR_VALUERECOMMENDER_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_WORKER_HTTP_PORT("CEDAR_WORKER_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_WORKER_ADMIN_PORT("CEDAR_WORKER_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_WORKER_STOP_PORT("CEDAR_WORKER_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_OPENVIEW_HTTP_PORT("CEDAR_OPENVIEW_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_OPENVIEW_ADMIN_PORT("CEDAR_OPENVIEW_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_OPENVIEW_STOP_PORT("CEDAR_OPENVIEW_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_INTERNALS_HTTP_PORT("CEDAR_INTERNALS_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_INTERNALS_ADMIN_PORT("CEDAR_INTERNALS_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_INTERNALS_STOP_PORT("CEDAR_INTERNALS_STOP_PORT", CedarEnvironmentVariableType.NUMERIC),

  CEDAR_IMPEX_HTTP_PORT("CEDAR_IMPEX_HTTP_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_IMPEX_ADMIN_PORT("CEDAR_IMPEX_ADMIN_PORT", CedarEnvironmentVariableType.NUMERIC),
  CEDAR_IMPEX_STOP_PORT("CEDAR_IMPEX_STOP_PORT", CedarEnvironmentVariableType.NUMERIC);

  private final String name;
  private final CedarEnvironmentVariableSecure secure;
  private final CedarEnvironmentVariableType type;

  CedarEnvironmentVariable(String name) {
    this.name = name;
    this.secure = CedarEnvironmentVariableSecure.NO;
    this.type = CedarEnvironmentVariableType.STRING;
  }

  CedarEnvironmentVariable(String name, CedarEnvironmentVariableType type) {
    this.name = name;
    this.secure = CedarEnvironmentVariableSecure.NO;
    this.type = type;
  }

  CedarEnvironmentVariable(String name, CedarEnvironmentVariableSecure secure) {
    this.name = name;
    this.secure = secure;
    this.type = CedarEnvironmentVariableType.STRING;
  }

  public String getName() {
    return name;
  }

  public boolean isNumeric() {
    return type == CedarEnvironmentVariableType.NUMERIC;
  }

  public boolean isBoolean() {
    return type == CedarEnvironmentVariableType.BOOLEAN;
  }

  public boolean isSecure() {
    return secure == CedarEnvironmentVariableSecure.YES;
  }

  public static CedarEnvironmentVariable forName(String name) {
    for (CedarEnvironmentVariable ev : values()) {
      if (ev.getName().equals(name)) {
        return ev;
      }
    }
    return null;
  }
}
